### ISSUE TITLE
Compile error when starting server

### ISSUE THREAD

**Issue by ChristianPresslmayr** [nkl-kst/MMM-OnThisDay#23]
Hi!
After installing the module and configuring it, I tried to start my server again, but this fails due to a compile error:

[22.02.2022 09:02.35.807] [ERROR] WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/modules/MMM-OnThisDay/EventService.js:18
    _html = '';
          ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-OnThisDay/node_helper.js:10:22)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)

(Note: the up-arrow in the error message points at the equal-sign)

Any idea what's wrong here?

**Comment by ChristianPresslmayr** [comment]
Don't know what I did, but when I tried again today, it works (probably some update of MagicMirror solved it).

So closing this issue

**Comment by nkl-kst** [comment]
Glad to hear it works now :)

11.11.2022 10:49:13 Christian Presslmayr ***@***.***>:
